// This file is autogenerated. Do not edit directly.
#pragma once
#include <unordered_map>
#include <string_view>
#include <memory>
#include <functional>

#include "Bug.cpp"
#include "Dark.cpp"
#include "Dragon.cpp"
#include "Electric.cpp"
#include "Fairy.cpp"
#include "Fighting.cpp"
#include "Fire.cpp"
#include "Flying.cpp"
#include "Ghost.cpp"
#include "Grass.cpp"
#include "Ground.cpp"
#include "Ice.cpp"
#include "Normal.cpp"
#include "Poison.cpp"
#include "Psychic.cpp"
#include "Rock.cpp"
#include "Steel.cpp"
#include "Stellar.cpp"
#include "Water.cpp"

inline std::unordered_map<std::string_view, std::function<std::unique_ptr<Type>()>> TypeFactory = {
    {"Bug", []() -> std::unique_ptr<Type> { return std::make_unique<Bug>(); }},
    {"Dark", []() -> std::unique_ptr<Type> { return std::make_unique<Dark>(); }},
    {"Dragon", []() -> std::unique_ptr<Type> { return std::make_unique<Dragon>(); }},
    {"Electric", []() -> std::unique_ptr<Type> { return std::make_unique<Electric>(); }},
    {"Fairy", []() -> std::unique_ptr<Type> { return std::make_unique<Fairy>(); }},
    {"Fighting", []() -> std::unique_ptr<Type> { return std::make_unique<Fighting>(); }},
    {"Fire", []() -> std::unique_ptr<Type> { return std::make_unique<Fire>(); }},
    {"Flying", []() -> std::unique_ptr<Type> { return std::make_unique<Flying>(); }},
    {"Ghost", []() -> std::unique_ptr<Type> { return std::make_unique<Ghost>(); }},
    {"Grass", []() -> std::unique_ptr<Type> { return std::make_unique<Grass>(); }},
    {"Ground", []() -> std::unique_ptr<Type> { return std::make_unique<Ground>(); }},
    {"Ice", []() -> std::unique_ptr<Type> { return std::make_unique<Ice>(); }},
    {"Normal", []() -> std::unique_ptr<Type> { return std::make_unique<Normal>(); }},
    {"Poison", []() -> std::unique_ptr<Type> { return std::make_unique<Poison>(); }},
    {"Psychic", []() -> std::unique_ptr<Type> { return std::make_unique<Psychic>(); }},
    {"Rock", []() -> std::unique_ptr<Type> { return std::make_unique<Rock>(); }},
    {"Steel", []() -> std::unique_ptr<Type> { return std::make_unique<Steel>(); }},
    {"Stellar", []() -> std::unique_ptr<Type> { return std::make_unique<Stellar>(); }},
    {"Water", []() -> std::unique_ptr<Type> { return std::make_unique<Water>(); }},
};
