// This file is autogenerated. Do not edit directly.
#pragma once
#include <unordered_map>
#include <string_view>
#include <memory>
#include <functional>

#include "Magikarp.cpp"
#include "Pikachu.cpp"

inline std::unordered_map<std::string_view, std::function<std::unique_ptr<Pokemon>()>> TypeFactory = {
    {"Magikarp", []() -> std::unique_ptr<Pokemon> { return std::make_unique<Magikarp>(); }},
    {"Pikachu", []() -> std::unique_ptr<Pokemon> { return std::make_unique<Pikachu>(); }},
};
