#!/usr/bin/env python3
"""
Generate a /Data/All.hpp that includes every .cpp file in the directory.

Usage: generate_all_hpp.py <folder_with_Data> 
Example: generate_all_hpp.py Types Types/Data/All.hpp
"""
import sys
from pathlib import Path


def generate(data_dir: Path, out_path: Path) -> None:
    if not data_dir.is_dir():
        raise SystemExit(f"Data directory not found: {data_dir}")

    cpp_files = sorted(p.name for p in data_dir.iterdir() if p.suffix == '.cpp')

    lines = ["// This file is autogenerated. Do not edit directly.", "#pragma once", ""]
    for name in cpp_files:
        # skip the generated header itself if it ever appears
        if name == out_path.name:
            continue
        lines.append(f'#include "{name}"')

    content = "\n".join(lines) + "\n"

    # write only if changed to avoid unnecessary rebuilds
    if out_path.exists() and out_path.read_text(encoding='utf-8') == content:
        return

    out_path.parent.mkdir(parents=True, exist_ok=True)
    tmp = out_path.with_suffix(out_path.suffix + '.tmp')
    tmp.write_text(content, encoding='utf-8')
    tmp.replace(out_path)
    

def main(argv):
    if len(argv) != 2:
        print("Usage: generate_all_hpp.py <dir>")
        return 2
    data_dir = Path(argv[1])
    generate(data_dir / "Data", data_dir / "Data" / "All.hpp")
    return 0


if __name__ == '__main__':
    raise SystemExit(main(sys.argv))
