#!/usr/bin/env python3
"""
Generate `Data/All.hpp` that includes every .cpp file in the directory and
emits an inline factory map that returns `std::unique_ptr<Type>` for each
concrete type.

Usage: generate_all_hpp.py <folder_with_Data>
Example: generate_all_hpp.py Types
This will write `Types/Data/All.hpp`.
"""
import sys
from pathlib import Path


def generate(data_dir: Path, out_path: Path) -> None:
    if not data_dir.is_dir():
        raise SystemExit(f"Data directory not found: {data_dir}")

    cpp_files = sorted(p.name for p in data_dir.iterdir() if p.suffix == '.cpp')

    lines = [
        "// This file is autogenerated. Do not edit directly.",
        "#pragma once",
        "#include <unordered_map>",
        "#include <string_view>",
        "#include <memory>",
        "#include <functional>",
        "",
    ]

    # includes for concrete type implementations
    for name in cpp_files:
        if name == out_path.name:
            continue
        lines.append(f'#include "{name}"')

    lines.append("")

    convtable = {
        "Types": "Type",
        "Pokemon"   : "Pokemon",
        "Moves"     : "Move",
        "Conditions" : "Condition",
        "Abilities" : "Ability",
        "Items"     : "Item",
        }

    # map: string_view -> function returning unique_ptr<Type>
    lines.append(
        f"inline std::unordered_map<std::string_view, std::function<std::unique_ptr<{convtable.get(data_dir.parent.name)}>()>> {convtable.get(data_dir.parent.name)}Factory = {{"
    )

    entries = []
    for name in cpp_files:
        if name == out_path.name:
            continue
        base = name.rsplit('.', 1)[0]
        entries.append(
            f'    {{"{base}", []() -> std::unique_ptr<{convtable.get(data_dir.parent.name)}> {{ return std::make_unique<{base}>(); }}}}'
        )

    if entries:
        # join entries with commas and add trailing comma for cleanliness
        lines.append(",\n".join(entries) + ",")

    lines.append("};")

    content = "\n".join(lines) + "\n"

    # write only if changed to avoid unnecessary rebuilds
    if out_path.exists() and out_path.read_text(encoding='utf-8') == content:
        return

    out_path.parent.mkdir(parents=True, exist_ok=True)
    tmp = out_path.with_suffix(out_path.suffix + '.tmp')
    tmp.write_text(content, encoding='utf-8')
    tmp.replace(out_path)


def main(argv):
    if len(argv) != 2:
        print("Usage: generate_all_hpp.py <dir>")
        return 2
    data_dir = Path(argv[1])
    generate(data_dir / "Data", data_dir / "Data" / "All.hpp")
    return 0


if __name__ == '__main__':
    raise SystemExit(main(sys.argv))
